#COLORS (ANSI)
dark_background_color: dce0e8 #crust
background_color: eff1f5
light_background_color: ccd0da #surface0 #black_color
lighter_background_color: bcc0cc  #alt_black_color
darker_foreground_color: 8c8fa1 #overlay1 #alt_white_color
dark_foreground_color: 7c7f93 #white_color
foreground_color: 4c4f69
red_color: d20f39	
green_color: 40a02b
yellow_color: df8e1d
blue_color: 1e66f5
magenta_color: ea76cb
cyan_color: 179299
alt_red_color: d20f39
alt_green_color: 40a02b
alt_yellow_color: df8e1d
alt_blue_color: 1e66f5
alt_magenta_color: ea76cb
alt_cyan_color: 179299

wallpaper_color: 209fb5

theme_style: light #either dark or light
#vim
vim_theme_plug: "Plug 'catppuccin/nvim', { 'as': 'catppuccin' }"
vim_theme_name: catppuccin-latte
