#COLORS (ANSI)
background_color: 282828
foreground_color: ebdbb2
black_color: 504945
red_color: cc241d	
green_color: 98971a
yellow_color: d79921
blue_color: 458588
magenta_color: b16286
cyan_color: 689d6a
white_color: d5c4a1	
alt_black_color: 665c54
alt_red_color: fb4934
alt_green_color: b8bb26
alt_yellow_color: fabd2f
alt_blue_color: 83a598
alt_magenta_color: d3869b
alt_cyan_color: 8ec07c
alt_white_color: bdae93

alt_foreground_color: 504945
#vim
#gtk
gtk_theme_package: gruvbox-dark-gtk
gtk_theme_name: gruvbox-dark-gtk
gtk_icon_name: Papirus-Dark
#qt
qt_theme_name: gruvbox
